update readme dynamic badges

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -100,15 +100,16 @@ jobs:
         CODE_COVERAGE_BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-${COVERAGE_COLOR}.svg"
         PYTEST_STATUS_BADGE_URL="https://img.shields.io/badge/PyTest-${TESTS_STATUS}-${TESTS_COLOR}.svg"
 
-        # Echo the badge URLs immediately
-        echo "Total test badge URL: $TOTAL_TESTS_BADGE_URL"
-        echo "Code coverage badge URL: $CODE_COVERAGE_BADGE_URL"
-        echo "PyTest status badge URL: $PYTEST_STATUS_BADGE_URL"
-
         # Export the badge URLs to the GitHub environment for use in later steps
         echo "TOTAL_TESTS_BADGE_URL=$TOTAL_TESTS_BADGE_URL" >> $GITHUB_ENV
         echo "CODE_COVERAGE_BADGE_URL=$CODE_COVERAGE_BADGE_URL" >> $GITHUB_ENV
         echo "PYTEST_STATUS_BADGE_URL=$PYTEST_STATUS_BADGE_URL" >> $GITHUB_ENV
+
+        # Echo the badge URLs
+        echo "Total test badge URL: $TOTAL_TESTS_BADGE_URL"
+        echo "Code coverage badge URL: $CODE_COVERAGE_BADGE_URL"
+        echo "PyTest status badge URL: $PYTEST_STATUS_BADGE_URL"
+
 
     - name: Update README with pylint badge
       run: |
@@ -125,17 +126,30 @@ jobs:
 
         # Generate badge URL
         PYLINT_BADGE_URL="https://img.shields.io/badge/pylint-${SCORE}-${COLOR}.svg"
-        echo $PYLINT_BADGE_URL
+        echo "PYLINT_BADGE_URL=$PYLINT_BADGE_URL" >> $GITHUB_ENV
+        echo "PyTest status badge URL: $PYLINT_BADGE_URL"
 
 
     - name: Update README with pyright badge
       run: |
+        # Generate badge URL
         BADGE_COLOR=$( [ $PYRIGHT_EXIT_CODE -eq 0 ] && echo "passing-brightgreen" || echo "failing-red" )
         PYRIGHT_BADGE_URL="https://img.shields.io/badge/pyright-${BADGE_COLOR}.svg"
-        echo "Updating README with badge URL: $PYRIGHT_BADGE_URL"
-        sed -i '/!\[Pyright Analysis\]/c\![Pyright Analysis]('"$PYRIGHT_BADGE_URL"')' README.md
+        echo "PYRIGHT_BADGE_URL=$PYRIGHT_BADGE_URL" >> $GITHUB_ENV
+        echo "PyTest status badge URL: $PYRIGHT_BADGE_URL"
+        
+    - name: Update README with all the badges
+      run: |
+        sed -i '/!\[badge_pylint\]/c\![badge_pylint]('"$PYLINT_BADGE_URL"')' README.md
+        sed -i '/!\[badge_pyright\]/c\![badge_pyright]('"$PYRIGHT_BADGE_URL"')' README.md
+        sed -i '/!\[badge_total_tests\]/c\![badge_total_tests]('"$TOTAL_TESTS_BADGE_URL"')' README.md
+        sed -i '/!\[badge_code_coverage\]/c\![badge_code_coverage]('"$CODE_COVERAGE_BADGE_URL"')' README.md
+        sed -i '/!\[badge_pytest_status\]/c\![badge_pytest_status]('"$PYTEST_STATUS_BADGE_URL"')' README.md
+
+        
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        rm -rf tmp
         if git diff --quiet; then
             echo "No changes to commit"
         else
@@ -155,5 +169,12 @@ jobs:
       run: |
         if [ ${{ env.PYLINT_EXIT_CODE }} -ne 0 ]; then
           echo "Pylint failed, marking job as failed."
+          exit 1
+        fi
+
+    - name: Fail if pytest failed
+      run: |
+        if [ ${{ env.PYTEST_EXIT_CODE }} -ne 0 ]; then
+          echo "Pytest failed, marking job as failed."
           exit 1
         fi
