env bug

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -64,10 +64,16 @@ jobs:
       run: |
         pyright src/* tests/*
       continue-on-error: true 
+    - name: Determine badge color
+      run: |
+        if [ $? -eq 0 ]; then
+          echo "PYRIGHT_BADGE_COLOR=passing-brightgreen" >> $GITHUB_ENV
+        else
+          echo "PYRIGHT_BADGE_COLOR=failing-red" >> $GITHUB_ENV
+        fi
     - name: Update README with badge
       run: |
-        BADGE_COLOR=$(if [ $? -eq 0 ]; then echo "passing-brightgreen"; else echo "failing-red"; fi)
-        BADGE_URL="https://img.shields.io/badge/pyright-${{ BADGE_COLOR }}.svg"
+        BADGE_URL="https://img.shields.io/badge/pyright-${{ env.BADGE_COLOR }}.svg"
         sed -i '/!\[Pyright Analysis\]/c\![Pyright Analysis]('"$BADGE_URL"')' README.md
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
