fail pyright at the end

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -75,14 +75,20 @@ jobs:
         sed -i '/!\[Pyright Analysis\]/c\![Pyright Analysis]('"$BADGE_URL"')' README.md
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git status
         if git diff --quiet; then
             echo "No changes to commit"
         else
-            git commit -am "Update Pyright badge in README"
+            git add README.md
+            git commit -m "Update Pyright badge in README"
             git push
         fi
         
+    - name: Fail if pyright failed
+      run: |
+        if [ ${{ env.PYRIGHT_EXIT_CODE }} -ne 0 ]; then
+          echo "Pyright failed, marking job as failed."
+          exit 1
+        fi
         
   test:
     runs-on: ubuntu-latest
