custom pylint dynamic badge

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -61,11 +61,36 @@ jobs:
       run: |
         rm -rf pylint_score.txt
 
+    - name: Run pylint
+      run: |
+        pylint src tests > pylint_output.txt
+        echo "PYLINT_OUTPUT=$(cat pylint_output.txt)" >> $GITHUB_ENV
+        echo "PYLINT_EXIT_CODE=$?" >> $GITHUB_ENV
+      continue-on-error: true 
+
     - name: Run pyright
       run: |
         pyright src/* tests/*
         echo "PYRIGHT_EXIT_CODE=$?" >> $GITHUB_ENV
       continue-on-error: true 
+
+    - name: Update README with pylint badge
+      run: |
+        SCORE=$(echo "$PYLINT_OUTPUT" | grep -oP '(?<=rated at )[0-9]+\.[0-9]+')
+        if [ "$SCORE" -lt 5 ]; then
+          COLOR="red"
+        elif [ "$SCORE" -lt 8 ]; then
+          COLOR="orange"
+        elif [ "$SCORE" -lt 10 ]; then
+          COLOR="yellow"
+        else
+          COLOR="brightgreen"
+        fi
+
+        # Generate badge URL
+        BADGE_URL="https://img.shields.io/badge/pylint-${SCORE}_out_of_10-${COLOR}.svg"
+        echo $BADGE_URL
+
 
     - name: Update README with pyright badge
       run: |
@@ -90,6 +115,12 @@ jobs:
           exit 1
         fi
         
+    - name: Fail if pylint failed
+      run: |
+        if [ ${{ env.PYLINT_EXIT_CODE }} -ne 0 ]; then
+          echo "Pylint failed, marking job as failed."
+          exit 1
+        fi
   test:
     runs-on: ubuntu-latest
     steps:
