refactoring

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -31,7 +31,7 @@ jobs:
         git commit -m "Auto format code with autopep8" || echo "No changes to commit"
         git push || echo "No changes to push"
 
-  badges:
+  lint_test_badges:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
@@ -43,28 +43,22 @@ jobs:
       run: |
         mkdir tmp
         sudo apt-get install -y libxml2-utils
-    - name: Install dependencies
-      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
     - name: Run pylint
+      continue-on-error: true
       run: |
         pylint src tests > tmp/pylint_output.txt || echo "PYLINT_EXIT_CODE=$?" >> $GITHUB_ENV
         cat tmp/pylint_output.txt
-      continue-on-error: true 
-
     - name: Run pyright
+      continue-on-error: true
       run: |
         pyright src/* tests/* || echo "PYRIGHT_EXIT_CODE=$?" >> $GITHUB_ENV
-      continue-on-error: true 
-
     - name: Run pytest
+      continue-on-error: true
       run: |
         pytest --cov=src --cov-report=json:tmp/coverage.json --junitxml=tmp/pytest_output.xml || echo "PYTEST_EXIT_CODE=$?" >> $GITHUB_ENV
-
-      continue-on-error: true
-
     - name: Extract number of tests, coverage, and determine result
       run: |
         NUM_TESTS=$(xmllint --xpath 'string(//testsuite/@tests)' tmp/pytest_output.xml)
@@ -109,6 +103,33 @@ jobs:
         echo "Code coverage badge URL: $CODE_COVERAGE_BADGE_URL"
         echo "PyTest status badge URL: $PYTEST_STATUS_BADGE_URL"
 
+
+    - name: Generate pylint badge url
+      run: |
+        SCORE=$(grep -oP '(?<=rated at )[0-9]+\.[0-9]+' tmp/pylint_output.txt)
+        if [ "$(echo "$SCORE < 5" | bc)" -eq 1 ]; then
+          COLOR="red"
+        elif [ "$(echo "$SCORE < 8" | bc)" -eq 1 ]; then
+          COLOR="orange"
+        elif [ "$(echo "$SCORE < 10" | bc)" -eq 1 ]; then
+          COLOR="yellow"
+        else
+          COLOR="brightgreen"
+        fi
+
+        # Generate badge URL
+        PYLINT_BADGE_URL="https://img.shields.io/badge/pylint-${SCORE}-${COLOR}"
+        echo "PYLINT_BADGE_URL=$PYLINT_BADGE_URL" >> $GITHUB_ENV
+        echo "PyTest status badge URL: $PYLINT_BADGE_URL"
+
+    - name: Generate pyright badge url
+      run: |
+        # Generate badge URL
+        BADGE_COLOR=$( [ $PYRIGHT_EXIT_CODE -eq 0 ] && echo "passing-brightgreen" || echo "failing-red" )
+        PYRIGHT_BADGE_URL="https://img.shields.io/badge/pyright-${BADGE_COLOR}"
+        echo "PYRIGHT_BADGE_URL=$PYRIGHT_BADGE_URL" >> $GITHUB_ENV
+        echo "PyTest status badge URL: $PYRIGHT_BADGE_URL"
+        
     - name: Update README with all the badges
       run: |
         sed -i '/!\[badge_pylint\]/c\![badge_pylint]('"$PYLINT_BADGE_URL"')' README.md
@@ -134,25 +155,12 @@ jobs:
         
     - name: Fail if any tool failed
       run: |
-
-        echo "PYLINT_EXIT_CODE: ${{ env.PYLINT_EXIT_CODE }}"
-        echo "PYRIGHT_EXIT_CODE: ${{ env.PYRIGHT_EXIT_CODE }}"
-        echo "PYTEST_EXIT_CODE: ${{ env.PYTEST_EXIT_CODE }}"
-        
         for TOOL in PYRIGHT PYLINT PYTEST; do
           EXIT_CODE_VAR="${TOOL}_EXIT_CODE"
           EXIT_CODE="${!EXIT_CODE_VAR}"
 
-          # Debugging output to check if the exit code is being retrieved correctly
           echo "Checking exit code for $TOOL: $EXIT_CODE"
 
-          # Ensure that the EXIT_CODE variable is not empty
-          if [ -z "$EXIT_CODE" ]; then
-            echo "Warning: $EXIT_CODE_VAR is not set or empty."
-            continue
-          fi
-
-          # Check if the exit code indicates a failure
           if [ "$EXIT_CODE" -ne 0 ]; then
             echo "$TOOL failed, marking job as failed."
             exit 1
